import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import FolderOpenIcon from '@mui/icons-material/FolderOpen';
import * as React from 'react';
import Box from '@mui/material/Box';
import { Typography, Button, AppBar, Tabs,Tab} from '@mui/material'
import ArrowForwardIcon from '@mui/icons-material/ArrowForward';
import { useState } from 'react'
import StandaloneToggleButton from '@/components/togle';
import {ToggleButtonNotEmpty} from '@/components/togle2';
import { makeStyles } from '@material-ui/core/styles';
import LaptopIcon from '@material-ui/icons/Laptop';
import TvIcon from '@material-ui/icons/Tv';
import PhoneAndroidIcon from '@material-ui/icons/PhoneAndroid';
import Grid from '@material-ui/core/Grid';
import { ToggleButton } from '@mui/lab';
import {ToggleButtonGroup} from '@mui/lab';




const inter = Inter({ subsets: ['latin'] })


export default function Home() {


  const[estilos,setEstilos]=useState({
    width:500,
    backgroundColor:'yellow' })
   
   
  const cambiarAncho=(ancho:any)=>{
    const estilosCopia={...estilos};
    estilosCopia.width=ancho;
    setEstilos(estilosCopia);
    }

    

  let buttonStyle={
    backgroundColor: 'blue'
  }

{


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

<Box height="100vh" display="flex" flexDirection="column"
sx={{position: "absolute"}} >
<Typography variant="h5">Simple centered CTA</Typography>
<Typography variant="caption" display="block">
<FolderOpenIcon></FolderOpenIcon>         ./src/blocks/cta/CtaSimpleCentered/CtaSimpleCentered.js|ts</Typography>

<Box sx={{ bgcolor: 'white',
 height: 500,width:1250 ,
 borderColor: 'primary.main' ,
 borderRadius:2, 
 border: 1}}> 
 
 <Box height={70}
  sx={{ borderBottom: 1  }}>


 <Box
  m={2} //margin
  display="flex"
  justifyContent="flex-start"
  alignItems="flex-start"
  
>

 <Button variant="contained" color="secondary"
 endIcon={<ArrowForwardIcon/>}>
Get the code 
</Button>
 </Box>

<Box  m={2}
  display="flex"
  justifyContent="flex-end"
  alignItems="flex-end"
  sx={{ position: "relative", bottom:50 }}>
<StandaloneToggleButton></StandaloneToggleButton>
</Box>


<Box  
sx={{ position: "relative",left:380, bottom:115 }} >

<Grid container spacing={2}>
 <Grid item sm={12} md={6}>
</Grid>
<Grid item sm={12} md={6}>
<ToggleButtonGroup >
<ToggleButton value="laptop" aria-label="laptop">
<LaptopIcon 
            onClick=
            {(e)=>cambiarAncho(400)} />
            </ToggleButton >
            <ToggleButton value="tv" aria-label="tv">
              <TvIcon
              onClick=
              {(e)=>cambiarAncho(500)} 
              />
            </ToggleButton>
            <ToggleButton >
              <PhoneAndroidIcon  
              onClick=
              {(e)=>cambiarAncho(600)}/>
            </ToggleButton>
          </ToggleButtonGroup>
        </Grid>
    </Grid>
</Box>
 </Box>




<Box id="app-content" style={estilos}>
hola
<Typography variant='h1'>

</Typography> </Box>
 
 
 


 </Box>



      </Box>

      </main>
    </>
  )
}


}